### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by DerMuffin** [MehdiRtal/MicrosoftRewardsBot#23] opened 2022-10-19 05:53 UTC
Hey,

when running via workflow, latest update shows this when i try to run it.

"ModuleNotFoundError: No module named 'packaging'"

Exitcode 1

**Comment by nigh95ms** [comment] 2022-10-20 03:33
Same problem here,


```
Traceback (most recent call last):
  File "/home/runner/work/ms/ms/MicrosoftRewardsBot.py", line 15, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 7, in <module>
    from webdriver_manager.drivers.chrome import ChromeDriver
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 1, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
Error: Process completed with exit code 1.
```

**Comment by MehdiRtal** [comment] 2022-10-20 09:39
Can you update your fork, it should be fixed by now.

**Comment by nigh95ms** [comment] 2022-10-20 18:07
Ok, thanks!

**Comment by mgrimace** [comment] 2022-10-23 18:16
Mine is up to date but now it looks like when the Deploy schedule runs it runs for ~6hrs after repeated log-in timeouts with error `[ERROR] Time out raised.`

**Comment by mgrimace** [comment] 2022-10-23 18:17
It looks like it's the second account (the first seems to complete successfully)

**Comment by DerMuffin** [comment] 2022-10-24 07:03
Can confirm. This also happends on a local machine.

Seems like something with the mobile Search is wrong. When i dont run it headless, it stucks on the point where the scripts checks if you logged in into bing (on mobile page!). When i manually open that account registercard (three Bars in the upper right corner). It starts to search in the mobile interface.

Can also confirm that some accounts dont have this issue. Maybe some sort of cache.

**Comment by MehdiRtal** [comment] 2022-10-24 21:34
`[ERROR] Time out raised.` get raised when there's an error on login.

**Comment by DerMuffin** [comment] 2022-10-25 06:05
Initial Login works. The Error happends when starting Desktop or Mobile Search.

Ensuring login on Bing... <-- Here

**Comment by gdrhzrd6e** [comment] 2022-10-25 09:23
i know what the problem is i put in the other issue

**Comment by gdrhzrd6e** [comment] 2022-10-25 09:24
its just that it can't find the page elements cause theres an overlay telling you to install something its blue

**Comment by gdrhzrd6e** [comment] 2022-10-25 09:25
sometimes it doesn't appear

**Comment by gdrhzrd6e** [comment] 2022-10-25 09:29
i had to manually install packaging was it not in requirements?

**Comment by gdrhzrd6e** [comment] 2022-10-25 09:33
the promotion may only appear in some countries

**Closed** 2022-10-26 06:18 UTC
